#
# For running some services on development without tainting your system
#
version: '2'
services:

  redis:
    image: "redis:alpine"
    container_name: slack-development-redis
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis:/data'

  postgres:
    image: "postgres:alpine"
    container_name: slack-development-postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
     POSTGRES_PASSWORD: slack_development_not_random_password
     POSTGRES_DB: slack_development
     POSTGRES_USER: slack_development

volumes:
  redis:
  postgres:
